version: '3'

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80" # map port 8080 on my localhost to 80 inside the container
    deploy:
      mode: replicated
      replicas: 1